# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ShowHide = QtWidgets.QCheckBox(self.layoutWidget)
        self.ShowHide.setObjectName("ShowHide")
        self.gridLayout.addWidget(self.ShowHide, 1, 0, 1, 1)
        self.ChannelsMenu = QtWidgets.QComboBox(self.layoutWidget)
        self.ChannelsMenu.setObjectName("ChannelsMenu")
        self.ChannelsMenu.addItem("")
        self.ChannelsMenu.addItem("")
        self.ChannelsMenu.addItem("")
        self.gridLayout.addWidget(self.ChannelsMenu, 0, 1, 1, 1)
        self.BrowseButtonB = QtWidgets.QPushButton(self.layoutWidget)
        self.BrowseButtonB.setObjectName("BrowseButtonB")
        self.gridLayout.addWidget(self.BrowseButtonB, 3, 0, 1, 2)
        self.Channel_label = QtWidgets.QLabel(self.layoutWidget)
        self.Channel_label.setObjectName("Channel_label")
        self.gridLayout.addWidget(self.Channel_label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.EditLabelLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditLabelLine.setObjectName("EditLabelLine")
        self.gridLayout.addWidget(self.EditLabelLine, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PausePlayBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.PausePlayBtn.setObjectName("PausePlayBtn")
        self.gridLayout_2.addWidget(self.PausePlayBtn, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.SpeedSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.SpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.gridLayout_2.addWidget(self.SpeedSlider, 2, 0, 1, 1)
        self.Speed_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Speed_label.setObjectName("Speed_label")
        self.gridLayout_2.addWidget(self.Speed_label, 1, 0, 1, 1)
        self.SpeedNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.SpeedNumber.setObjectName("SpeedNumber")
        self.gridLayout_2.addWidget(self.SpeedNumber, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Colour_label = QtWidgets.QLabel(self.layoutWidget2)
        self.Colour_label.setObjectName("Colour_label")
        self.gridLayout_3.addWidget(self.Colour_label, 1, 0, 1, 1)
        self.ColoursMenu = QtWidgets.QComboBox(self.layoutWidget2)
        self.ColoursMenu.setObjectName("ColoursMenu")
        self.gridLayout_3.addWidget(self.ColoursMenu, 1, 1, 1, 1)
        self.ExportBtn = QtWidgets.QPushButton(self.layoutWidget2)
        self.ExportBtn.setObjectName("ExportBtn")
        self.gridLayout_3.addWidget(self.ExportBtn, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayout_2.addWidget(self.verticalSlider)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalSlider_3 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.verticalLayout_3.addWidget(self.verticalSlider_3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 0, 4, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 7, 0, 1, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_6.addWidget(self.horizontalScrollBar, 1, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_6.addWidget(self.verticalScrollBar, 0, 0, 1, 1)
        self.Plot = PlotWidget(self.groupBox_2)
        self.Plot.setMinimumSize(QtCore.QSize(0, 100))
        self.Plot.setAutoFillBackground(False)
        self.Plot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Plot.setObjectName("Plot")
        self.gridLayout_6.addWidget(self.Plot, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Spectrogram = QtWidgets.QWidget(self.groupBox_3)
        self.Spectrogram.setMinimumSize(QtCore.QSize(300, 0))
        self.Spectrogram.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Spectrogram.setObjectName("Spectrogram")
        self.gridLayout_5.addWidget(self.Spectrogram, 0, 0, 1, 2)
        self.Spectro_label = QtWidgets.QLabel(self.groupBox_3)
        self.Spectro_label.setObjectName("Spectro_label")
        self.gridLayout_5.addWidget(self.Spectro_label, 1, 0, 1, 1)
        self.SpectroMenu = QtWidgets.QComboBox(self.groupBox_3)
        self.SpectroMenu.setObjectName("SpectroMenu")
        self.SpectroMenu.addItem("")
        self.SpectroMenu.addItem("")
        self.SpectroMenu.addItem("")
        self.gridLayout_5.addWidget(self.SpectroMenu, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.splitter_2, 2, 0, 2, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ZoomIn = QtWidgets.QPushButton(self.centralwidget)
        self.ZoomIn.setObjectName("ZoomIn")
        self.horizontalLayout_3.addWidget(self.ZoomIn)
        self.ZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.ZoomOut.setObjectName("ZoomOut")
        self.horizontalLayout_3.addWidget(self.ZoomOut)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 6, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 19))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 5, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 0))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_9.addWidget(self.line_5, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Control Center"))
        self.ShowHide.setText(_translate("MainWindow", "Hide"))
        self.ChannelsMenu.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.ChannelsMenu.setItemText(1, _translate("MainWindow", "Channel 2"))
        self.ChannelsMenu.setItemText(2, _translate("MainWindow", "Channel 3"))
        self.BrowseButtonB.setText(_translate("MainWindow", "Browse Files"))
        self.Channel_label.setText(_translate("MainWindow", "Select Channel"))
        self.label_5.setText(_translate("MainWindow", "Edit Label"))
        self.PausePlayBtn.setText(_translate("MainWindow", "Pause/Play"))
        self.Speed_label.setText(_translate("MainWindow", "Cine Speed"))
        self.Colour_label.setText(_translate("MainWindow", "Select Colour"))
        self.ExportBtn.setText(_translate("MainWindow", "Export"))
        self.label_4.setText(_translate("MainWindow", "Spectrogram Range"))
        self.label_2.setText(_translate("MainWindow", " Min"))
        self.label_3.setText(_translate("MainWindow", " Max"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Channels"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Spectrogram"))
        self.Spectro_label.setText(_translate("MainWindow", "Select Channel"))
        self.SpectroMenu.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.SpectroMenu.setItemText(1, _translate("MainWindow", "Channel 2"))
        self.SpectroMenu.setItemText(2, _translate("MainWindow", "Channel 3"))
        self.ZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.ZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Multi-Channel Signal Viewer</span></p></body></html>"))

from pyqtgraph import PlotWidget

